# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Riva Refuge
email: contact@rivarefuge.org
description: > # this means to ignore newlines until "baseurl:"
  Riva Refuge is a small, secular non-profit organization that helps children, 
  youth, young women, disabled, and elderly. Our mission is to 
  elevate the well-being of disadvantaged.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.rivarefuge.org" # the base hostname & protocol for your site
github_username:  rivarefuge
logo: /images/rrlogo-only.png

social:
  name: Riva Refuge
  links:
    - https://www.facebook.com/Riva-Refuge-Inc-177593545669926

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown

exclude:
  - params.json
  - .DS_Store
  - LICENSE
  - README.md
  - feed.xml
  - js/npm.js
  - js/bootstrap.js
  - js/bootstrap.min.js
  - css/bootstrap.min.css
  - css/bootstrap-theme.min.css
  - css/main.scss

sass:
  sass_dir: _sass
  style: compressed
  load_paths:
      - _sass
      - node_modules
  silence_deprecations:
      - import
      - global-builtin
      - color-functions